version: "3.9"

services:
  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolioDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Student1234
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: